spring:
  kafka:
    bootstrap-servers: localhost:9092

broker:
  main-url: http://localhost:8080
  sub-url: http://localhost:8080
  sub:
    max-requests: 10

management:
  metrics:
    export:
      cloudwatch:
        enabled: false